### ISSUE TITLE
Initial language?

### ISSUE THREAD

**Issue by lechten** [AaronHuemmecke/Sorting-Algorithm-Visualizer#3]
When I start the program, the German welcome text is displayed (with German also shown as selected language) while the navigation bar at the top shows English terms. Switching to English and back to German works as expected.

**Comment by AaronHuemmecke** [comment]
I guess that English is configured as the default language of your computer. This is partially recognized by the LanguageManager. I will set the language of the LanguageManager to German at the beginning of the program in order to ensure that only German texts will be displayed at start.

**Comment by lechten** [comment]
Languages are no longer mixed for me, but this is still not perfect. I work with English locale. Upon startup, the radio button pretends "German", but English texts and button labels are shown.

**Comment by lechten** [comment]
Fixed in latest release. Many thanks!
