### ISSUE TITLE
Window width?

### ISSUE THREAD

**Issue by lechten** [AaronHuemmecke/Sorting-Algorithm-Visualizer#4]
Does the window width need to be fixed? The width of 1280 pixels of my screen is not sufficient, causing an overflow to the neighboring screen...

**Comment by AaronHuemmecke** [comment]
The miminum width is currently defined as 1600 pixels.

Removing the minimum screen size setting entirely could lead to overlapping GUI elements, especially in the Algorithm Visualization section with the "show code and explanation", "show variable values" and "show live key figures" options turned on for complex sorting algorithms like MergeSort. With the current layout, the smallest possible width is 1200 pixels.

**Comment by lechten** [comment]
1200 pixels work for me. Thanks!
